import { Platform } from 'react-native'

const HORIZONTAL_SPACING_BASE = Platform.OS === 'web' ? 4 : 2
const VERTICAL_SPACING_BASE = 4

const icons = {
  playButton: require('../assets/icons/play-button.png'),
  logo: require('../assets/images/icon-bgless.png'),
  userAvatar: require('../assets/images/default-avatar.jpg'),
  backArrow: require('../assets/icons/arrow-back-icon.png'),
  fireIcon: require('../assets/images/fire-icon.png'),
  userProfile: require('../assets/images/person-filled-icon.png'),
  conversations: require('../assets/images/chat-filled-icon.png'),
  BackgroundLayer: require('../assets/images/layerson2.png'),
  Dislike: require('../assets/images/dislike.png'),
  SuperLike: require('../assets/images/super_like.png'),
  Like: require('../assets/images/heart-filled-icon.png'),
  Leaves_BG: require('../assets/images/bg.png'),
  home: require('../assets/icons/home-icon.png'),
  add_user: require('../assets/icons/add-user-icon.png'),
  add_user_filled: require('../assets/icons/add-user-icon-filled.png'),
  camera: require('../assets/icons/camera-icon.png'),
  cameraFilled: require('../assets/icons/camera-filled.png'),
  chat: require('../assets/icons/chat-icon.png'),
  close: require('../assets/icons/close-x-icon.png'),
  checked: require('../assets/icons/checked-icon.png'),
  delete: require('../assets/icons/delete.png'),
  friends: require('../assets/icons/friends-icon.png'),
  inscription: require('../assets/icons/inscription-icon.png'),
  menu: require('../assets/icons/menu.png'),
  private_chat: require('../assets/icons/private-chat-icon.png'),
  search: require('../assets/icons/search-icon.png'),
  share: require('../assets/icons/share-icon.png'),
  vip: require('../assets/icons/vip.png'),
  logout: require('../assets/images/logout-menu-item.png'),
  instagram: require('../assets/images/icons8-instagram-100.png'),
  account: require('../assets/images/account-male-icon.png'),
  setting: require('../assets/images/settings-menu-item.png'),
  callIcon: require('../assets/images/contact-call-icon.png'),
  schoolIcon: require('../assets/images/educate-school-icon.png'),
  markerIcon: require('../assets/images/icons8-marker-500.png'),
  arrowdownIcon: require('../assets/images/arrow-down-icon.png'),
  boederImgSend: require('../assets/images/borderImg1.png'),
  boederImgReceive: require('../assets/images/borderImg2.png'),
  textBoederImgSend: require('../assets/images/textBorderImg1.png'),
  textBoederImgReceive: require('../assets/images/textBorderImg2.png'),
  starFilled: require('../assets/images/star-filled-icon2.png'),
  crossFilled: require('../assets/images/cross-filled-icon.png'),
  blockedUser: require('../assets/icons/blocked-user-64.png'),
  Logo: require('../assets/images/Logo.png'),
  BackgroundLayer: require('../assets/images/layerson2.png'),
  Dislike: require('../assets/images/dislike.png'),
  SuperLike: require('../assets/images/super_like.png'),
  Like: require('../assets/images/heart-filled-icon.png'),
  camera: require('../assets/icons/camera-icon.png'),
  tick: require('../assets/icons/tick.png'),
  vip: require('../assets/icons/vip.png'),
  undo: require('../assets/icons/undo.png'),
  logout: require('../assets/images/logout-menu-item.png'),
  LogoHugsDating: require('../assets/images/LogoHugsDating.png'),
  instagram: require('../assets/images/icons8-instagram-100.png'),
  account: require('../assets/images/account-male-icon.png'),
  setting: require('../assets/images/settings-menu-item.png'),
  callIcon: require('../assets/images/contact-call-icon.png'),
  schoolIcon: require('../assets/images/educate-school-icon.png'),
  markerIcon: require('../assets/images/icons8-marker-500.png'),
  arrowdownIcon: require('../assets/images/arrow-down-icon.png'),
  boederImgSend: require('../assets/images/borderImg1.png'),
  boederImgReceive: require('../assets/images/borderImg2.png'),
  textBoederImgSend: require('../assets/images/textBorderImg1.png'),
  textBoederImgReceive: require('../assets/images/textBorderImg2.png'),
  starFilled: require('../assets/images/star-filled-icon2.png'),
  crossFilled: require('../assets/images/cross-filled-icon.png'),
}

const lightColors = {
  primaryBackground: '#ffffff',
  primaryBackgroundHighlight: '#f2f2f2',
  secondaryBackground: '#ffffff',
  primaryForeground: '#eb5a6d',
  secondaryForeground: '#f4f6fb',
  foregroundContrast: 'white',
  primaryText: '#464646',
  secondaryText: '#7e7e7e',
  placeholderColor: '#8c8c8c',
  hairline: '#e0e0e0',
  grey0: '#fafafa',
  grey3: '#f5f5f5',
  grey6: '#d6d6d6',
  grey9: '#939393',
  red: '#ea0606',
}

const InstamobileTheme = {
  colors: {
    light: lightColors,
    'no-preference': lightColors,
    dark: {
      primaryBackground: '#121212',
      primaryBackgroundHighlight: '#151515',
      secondaryBackground: '#000000',
      primaryForeground: '#eb5a6d',
      secondaryForeground: '#282828',
      foregroundContrast: 'white',
      primaryText: '#ffffff',
      secondaryText: '#c5c5c5',
      placeholderColor: '#8c8c8c',
      hairline: '#222222',
      grey0: '#0a0a0a',
      grey3: '#2a2a2a',
      grey6: '#f5f5f5',
      grey9: '#eaeaea',
      red: '#ea0606',
    },
  },
  spaces: {
    horizontal: {
      s: 2 * HORIZONTAL_SPACING_BASE,
      m: 4 * HORIZONTAL_SPACING_BASE,
      l: 6 * HORIZONTAL_SPACING_BASE,
      xl: 8 * HORIZONTAL_SPACING_BASE,
    },
    vertical: {
      s: 2 * VERTICAL_SPACING_BASE,
      m: 4 * VERTICAL_SPACING_BASE,
      l: 6 * VERTICAL_SPACING_BASE,
      xl: 8 * VERTICAL_SPACING_BASE,
    },
  },
  fontSizes: {
    xxs: 8,
    xs: 12,
    s: 14,
    m: 16,
    l: 18,
    xl: 24,
    xxl: 32,
  },
  fontWeights: {
    s: '400',
    m: '600',
    l: '800',
  },
  icons: icons,
  // color, font size, space / margin / padding, vstack / hstack
  button: {
    borderRadius: 8,
  },
}

export default InstamobileTheme
