import { IRoom } from "../Core/rooms/types";

export function useConfig(): IConfig

export const GOOGLE_MAPS_API_KEY: string

// Generated by https://quicktype.io

export interface IConfig {
    isSMSAuthEnabled:          boolean;
    appIdentifier:             string;
    facebookIdentifier:        string;
    webClientId:               string;
    onboardingConfig:          OnboardingConfig;
    tosLink:                   string;
    isUsernameFieldEnabled:    boolean;
    smsSignupFields:           SignupFieldElement[];
    signupFields:              SignupFieldElement[];
    privacyPolicyLink:         string;
    editProfileFields:         Fields;
    userSettingsFields:        Fields;
    contactUsFields:           ContactUsFields;
    dailySwipeLimit:           number;
    totalSwipeLimit:           number;
    subscriptionSlideContents: SubscriptionSlideContent[];
    contactUsPhoneNumber:      string;
    IAP_SHARED_SECRET:         string;
    IAP_SKUS:                  string[];
    rooms:                     IRoom[];
}

export interface ContactUsFields {
    sections: ContactUsFieldsSection[];
}

export interface ContactUsFieldsSection {
    title:  string;
    fields: PurpleField[];
}

export interface PurpleField {
    displayName:  string;
    type:         string;
    editable?:    boolean;
    key:          string;
    value?:       string;
    placeholder?: string;
}

export interface Fields {
    sections: EditProfileFieldsSection[];
}

export interface EditProfileFieldsSection {
    title:  string;
    fields: SignupFieldElement[];
}

export interface SignupFieldElement {
    displayName:      string;
    type:             string;
    editable?:        boolean;
    regex?:           Regex;
    key:              string;
    placeholder?:     string;
    options?:         string[];
    displayOptions?:  string[];
    autoCapitalize?:  string;
    secureTextEntry?: boolean;
    value?:           boolean | string;
}

export enum Regex {
    Asd = "asd",
    Asda = "asda",
}

export interface OnboardingConfig {
    welcomeTitle:       string;
    welcomeCaption:     string;
    walkthroughScreens: WalkthroughScreen[];
}

export interface WalkthroughScreen {
    icon:        string;
    title:       string;
    description: string;
}

export interface SubscriptionSlideContent {
    title:       string;
    description: string;
    src:         string;
}
